@startuml "Final Exam Project"

package "GUI Layer" {
    class EngineController {
        -Items: List<Item>
        -Baskets: List<Basket>
    }

    WinForms -- EngineController
}

package "Logic Layer" {
    class BasketManager {
        {static} +createItem()
        {static} +changeItem()
        {static} +createBasket()
        {static} +addItemToBasket()
        {static} +removeItemFromBasket()
        {static} +deleteItem()
        {static} +deleteBasket()
        {static} +undo()
    }

    abstract class Item << prototype >> {
        -Name: String
        -Color: String
        -Shape: String
        -Texture: String
        -Size: enum
        -Taste: enum
    }

    class Veggie extends Item {
        -Type: String
    }

    class Fruit extends Item {
        -Type: String
    }

    abstract class Basket {
        -Items: List<Item>
    }

    package Factory {
        class BasketFactory {
            +createBasket()
        }

        class FoodFactory {
            +createItem()
        }

        BasketFactory ..> Basket
        FoodFactory ..> Item

        EngineController -- BasketManager
        EngineController -- BasketFactory
        EngineController -- FoodFactory

        Basket --> "0..N" Item
    }
}

@enduml